controllers:
    resource: ../src/Controller/
    type: attribute

welcome_home:
    path: /welcome/{name}
    controller: App\Controller\HomeController::welcome
    requirements:
        name: '\d+'
